/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.starcrap.forms;

import br.com.fiap.starcrap.daos.EquipeDAO;
import br.com.fiap.starcrap.daos.FogueteDAO;
import br.com.fiap.starcrap.daos.LancamentoDAO;
import br.com.fiap.starcrap.models.Equipe;
import br.com.fiap.starcrap.models.Foguete;
import br.com.fiap.starcrap.models.Lancamento;
import java.math.BigDecimal;
import java.time.Duration;
import java.util.Arrays;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.*;

/**
 * @author go
 */
public class AltimetroForm extends javax.swing.JFrame {

	private Foguete foguete;
	private Lancamento lancamento;
	private Equipe equipe;
	private EntityManager manager;
	private LancamentoDAO lancamentoDAO;
	private FogueteDAO fogueteDAO;
	private EquipeDAO equipeDAO;

	/**
	 * Creates new form f
	 */
	public AltimetroForm(Equipe equipe,Lancamento lancamento, Foguete foguete) {
		this.manager = Persistence.createEntityManagerFactory("default").createEntityManager();
		this.foguete = foguete;
		this.lancamento = lancamento;
		this.equipe = equipe;
		this.lancamentoDAO = new LancamentoDAO(manager);
		this.fogueteDAO = new FogueteDAO(manager);
		this.equipeDAO = new EquipeDAO(manager);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		altitudeMax = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		velocidadeMax = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tempoPropulsao = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		picoAceleracao = new javax.swing.JTextField();
		tempoEjecao = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		altitudeEjecao = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		aceleracaoMedia = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		entreApogeu = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		taxaDescida = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		duracaoVoo = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		salvar = new javax.swing.JButton();
		voltar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Altitude M�xima");

		jLabel2.setText("Velocidade M�xima");

		jLabel3.setText("Tempo de Propuls�o");

		jLabel4.setText("Pico de Acelera��o");

		jLabel5.setText("Altitude de Eje��o");

		jLabel6.setText("Acelera��o Media");

		jLabel7.setText("Tempo entre Apogeu");

		jLabel8.setText("Tempo de Eje��o");

		jLabel9.setText("Dura��o do Voo");

		jLabel10.setText("Taxa de Descida");

		salvar.setText("Salvar");
		salvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salvarActionPerformed(evt);
			}
		});

		voltar.setText("Voltar");
		voltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				voltarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(aceleracaoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(altitudeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(velocidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(tempoPropulsao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(picoAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel7)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(entreApogeu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel8)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(tempoEjecao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel10)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(taxaDescida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel5)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(altitudeEjecao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel9)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(duracaoVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(voltar)
												.addGap(18, 18, 18)
												.addComponent(salvar)))
								.addContainerGap(42, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(altitudeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(velocidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(tempoPropulsao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4)
										.addComponent(picoAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel6)
										.addComponent(aceleracaoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel7)
										.addComponent(entreApogeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel8)
										.addComponent(tempoEjecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel5)
										.addComponent(altitudeEjecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel10)
										.addComponent(taxaDescida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9)
										.addComponent(duracaoVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(salvar)
										.addComponent(voltar))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
		LancamentoForm lancamento = new LancamentoForm(equipe);
		lancamento.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_voltarActionPerformed

	private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
		manager.getTransaction().begin();
		String altitude = altitudeMax.getText();
		lancamento.setAltitudeMaxima(new BigDecimal(altitude));
		String velocmax = velocidadeMax.getText();
		lancamento.setVelocidadeMaxima(new BigDecimal(velocmax));
		long tempoprop = Long.valueOf(tempoPropulsao.getText());
		lancamento.setTempoDePropulsao(Duration.ofSeconds(tempoprop));
		String picoacel = picoAceleracao.getText();
		lancamento.setPicoDeAceleracao(new BigDecimal(picoacel));
		String acelmedia = aceleracaoMedia.getText();
		lancamento.setAceleracaoMedia(new BigDecimal(acelmedia));
		long tempoapogeu = Long.valueOf(entreApogeu.getText());
		lancamento.setTempoEntreApogeu(Duration.ofSeconds(tempoapogeu));
		long tempoejecao = Long.valueOf(tempoEjecao.getText());
		lancamento.setTempoDeEjecao(Duration.ofSeconds(tempoejecao));
		String altitudeejecao = altitudeEjecao.getText();
		lancamento.setAltitudeDeEjecao(new BigDecimal(altitudeejecao));
		String taxadesc = taxaDescida.getText();
		lancamento.setTaxaDeDescida(new BigDecimal(taxadesc));
		long duracaovoo = Long.valueOf(duracaoVoo.getText());
		lancamento.setDuracaoDoVoo(Duration.ofSeconds(duracaovoo));
		lancamento.setFoguete(foguete);
		fogueteDAO.insert(foguete);
		lancamentoDAO.insert(lancamento);
		equipe.setLancamentos(Arrays.asList(lancamento));
		equipeDAO.update(equipe);
		manager.getTransaction().commit();
		fechaTransacao();
		JOptionPane.showMessageDialog(this, "Dados salvos com sucesso");
		PrincipalForm princiapal = new PrincipalForm();
		princiapal.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_salvarActionPerformed

	private void fechaTransacao() {
		if (manager.getTransaction().isActive()) {
			manager.getTransaction().commit();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField aceleracaoMedia;
	private javax.swing.JTextField altitudeEjecao;
	private javax.swing.JTextField altitudeMax;
	private javax.swing.JTextField duracaoVoo;
	private javax.swing.JTextField entreApogeu;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField picoAceleracao;
	private javax.swing.JButton salvar;
	private javax.swing.JTextField taxaDescida;
	private javax.swing.JTextField tempoEjecao;
	private javax.swing.JTextField tempoPropulsao;
	private javax.swing.JTextField velocidadeMax;
	private javax.swing.JButton voltar;
	// End of variables declaration//GEN-END:variables
}
