/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.starcrap.forms;

import br.com.fiap.starcrap.daos.AlunoDAO;
import br.com.fiap.starcrap.daos.EquipeDAO;
import br.com.fiap.starcrap.models.Aluno;
import br.com.fiap.starcrap.models.Equipe;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author go
 */
public class PrincipalForm extends javax.swing.JFrame {

    private EntityManager manager;
    private EquipeDAO equipeDAO;
    private AlunoDAO alunoDAO;
    private Equipe equipeSelecionada;

    public PrincipalForm() {
        this.manager = Persistence.createEntityManagerFactory("default").createEntityManager();
        this.alunoDAO = new AlunoDAO(manager);
        this.equipeDAO = new EquipeDAO(manager);
        initComponents();
        populaGrupoList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lancamentoButton = new javax.swing.JButton();
        buttonPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        grupoButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        grupoScroll = new javax.swing.JScrollPane();
        grupoList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        componentesScroll = new javax.swing.JScrollPane();
        componentesList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        numComponentes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lancamentoButton.setText("Lan�amento");
        lancamentoButton.setEnabled(false);
        lancamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancamentoButtonActionPerformed(evt);
            }
        });

        buttonPesquisar.setText("Pesquisa");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        grupoButton.setText("Adicionar");
        grupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        grupoList.setToolTipText("");
        grupoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                grupoListValueChanged(evt);
            }
        });
        grupoScroll.setViewportView(grupoList);

        jLabel2.setText("Grupo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(grupoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerButton))
                            .addComponent(grupoScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoButton)
                    .addComponent(removerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        componentesScroll.setViewportView(componentesList);

        jLabel3.setText("Componentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componentesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numComponentes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numComponentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lancamentoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonPesquisar)
                        .addGap(35, 35, 35)
                        .addComponent(lancamentoButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoButtonActionPerformed
        manager.getTransaction().begin();

        String grupo = JOptionPane.showInputDialog("Digite o nome do grupo:");
        if (grupo != null) {
            Equipe equipe = new Equipe();
            equipe.setNome(grupo);

            String turma = JOptionPane.showInputDialog("Digite o nome da turma:");

            if (turma != null) {
                equipe.setTurma(turma);
                int nAlunos = 0;
                try {
                    nAlunos = Integer.parseInt(JOptionPane.showInputDialog("Digite o número de alunos do grupo:"));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Digite somente números inteiros");
                }
                if (nAlunos > 0) {
                    List<Aluno> alunos = new ArrayList<>();

                    for (int k = 0; k < nAlunos; k++) {
                        Aluno aluno = new Aluno();
                        String alunome = JOptionPane.showInputDialog("Digite o nome do " + (k + 1) + "º aluno:");
                        if (alunome == null) {
                            break;
                        } else {

                            String rm = JOptionPane.showInputDialog("Digite o rm do aluno:");
                            if (rm == null) {
                                break;
                            } else {
                                aluno.setNome(alunome);
                                aluno.setRm(rm);

                                alunoDAO.insert(aluno);

                                alunos.add(aluno);
                            }
                        }
                    }

                    equipe.setAlunos(alunos);
                    equipeDAO.insert(equipe);
                    manager.getTransaction().commit();
                    populaGrupoList();
                }
            }
        }
        fechaTransacao();
    }//GEN-LAST:event_grupoButtonActionPerformed

    private void grupoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_grupoListValueChanged
        if (!grupoList.isSelectionEmpty()) {
            equipeSelecionada = (Equipe) grupoList.getSelectedValue();
            populaComponentesList(equipeSelecionada.getNome());
            numComponentes.setText("(" + String.valueOf(equipeSelecionada.getAlunos().size()) + ")");
            if (!lancamentoButton.isEnabled()) {
                lancamentoButton.setEnabled(true);
            }
        } else {
            numComponentes.setText("");
        }
    }//GEN-LAST:event_grupoListValueChanged

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        manager.getTransaction().begin();
        equipeDAO.delete(equipeSelecionada);
        manager.getTransaction().commit();
        populaGrupoList();
        limpaComponentesList();
        fechaTransacao();
    }//GEN-LAST:event_removerButtonActionPerformed

    private void lancamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancamentoButtonActionPerformed
        LancamentoForm lancamento = new LancamentoForm();
        lancamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lancamentoButtonActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
        PesquisarForm pesquisar = new PesquisarForm();
        pesquisar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void populaGrupoList() {
        DefaultListModel<Equipe> listModel = new DefaultListModel<>();
        List<Equipe> equipes = equipeDAO.findAll();
        if (equipes != null || !equipes.isEmpty()) {
            for (Equipe equipe : equipes) {
                listModel.addElement(equipe);
            }
        }
        grupoList.setModel(listModel);
    }

    private void populaComponentesList(String nomeEquipe) {
        DefaultListModel<Aluno> listModel = new DefaultListModel<>();
        Equipe equipe = equipeDAO.findByTeamName(nomeEquipe);
        if (equipe != null) {
            for (Aluno aluno : equipe.getAlunos()) {
                listModel.addElement(aluno);
            }
        }
        componentesList.setModel(listModel);
    }

    private void limpaComponentesList() {
        DefaultListModel<Aluno> listModel = new DefaultListModel<>();
        listModel.clear();
        componentesList.setModel(listModel);
    }

    private void fechaTransacao() {
        if (manager.getTransaction().isActive()) {
            manager.getTransaction().commit();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JList componentesList;
    private javax.swing.JScrollPane componentesScroll;
    private javax.swing.JButton grupoButton;
    private javax.swing.JList grupoList;
    private javax.swing.JScrollPane grupoScroll;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lancamentoButton;
    private javax.swing.JLabel numComponentes;
    private javax.swing.JButton removerButton;
    // End of variables declaration//GEN-END:variables
}
